### PR TITLE
Clean up Django settings

### LINKED ISSUE #220: Allow .env to have multiple inputs to TRUSTED_ORIGINS and ALLOWED_HOSTS
The current deployment workflow has a load to the `stage` Azure App Service slot, quick verification, then a swap to the `prod` slot. To do this, both `stage` and `prod` URLs need to be in the `CSRF_TRUSTED_ORIGINS` and `ALLOWED_HOSTS` settings variables.

### PR DESCRIPTION
**Pull request by TiCampbell**
- Removed variables already in `common_settings.py` from the other settings files
- Fixes #220 (the issue goes into detail on the use of TOML)

### CODE REVIEW

**Comment by TiCampbell** [comment]
@penoptech as I was going through this, I noticed line 120 in `common_settings.py` redefines the built-in `str`. I was going to call out each variable in the `common_settings` import (instead of the current `from common_settings import *`), but as far as I know this has been there forever and I didn't want to mess anything up by suddenly excluding it. Do you know what the implications of removing the redefinition from the rest of the app would be?

**Comment by TiCampbell** [comment]
A consideration of this change is that the containerized secrets are no longer stored as environment vars (they're loaded into a dictionary, the same way local secrets were loaded from JSON). This wasn't an issue for me in testing, and not having them as environment vars is probably better for security anyway.

**Comment by penoptech** [comment]
As I understand it, the redefined `str` function is locally scoped to the file that it's redefined in, so the only implications of undoing the redefinition would be contained to that particular file. I think we can rename the variable and it won't impact the application. We still should probably smoke test it once the change is made to be sure, but it looks to be a straight-forward, low-risk change.

**Comment by TiCampbell** [comment]
RE: renaming the redefined `str` function - sounds good, I'll add it to (keep it on?) the Issues, but I'm not too worried about it since it's locally-scoped. Thanks!

I made changes to the middleware to match #234, so that one will need to be merged first.

**Comment by TiCampbell** [comment]
@penoptech I added the hotfix for large data uploads to this branch for completeness; I recommend merging #248 before this PR.

**Review by penoptech — APPROVED** [review]
Resolved a merge conflict related to merging #248 before this PR.

**Pull request merged**
