### PR TITLE
Address and Household Bug Fixes

### PR DESCRIPTION
**Pull request by penoptech**
- Fixed client-side address state and zip code validation. Moved validation from JavaScript to HTML. Removed `stateNameToAbbreviation` function, as USPS address validation handles this for us
- Fixed client-side number of household members validation. Added validation to HTML input.
- Added labels for `Mailing Address` and `House Address` on Address page. Also, reordered the USPS validation, so `eligibility address` could be corrected before `mailing address`

### CODE REVIEW

**Review by TiCampbell — APPROVED** [review]
@penoptech I'm sorry for the confusion; I was looking for clarity on which address is being corrected on the `address_correction.html` page. While I was in there I just went ahead and made the changes (I also think `address.html` was already clear, so I took out the headers you had added).

**Review by penoptech — COMMENTED** [review]
@TiCampbell - These changes look good to me.

**Comment by penoptech** [comment]
@TiCampbell - I think because I was the original requestor I can't approve my own PR. I looked at the changes, which totally make sense. I think if you approve and merge the PR we should be good to go.

**Review by TiCampbell — APPROVED** [review]
Ah lame. Welp, my bad...here we go!

**Pull request merged**
