### PR TITLE
Admin panel creation

### PR DESCRIPTION
**Pull request by TiCampbell**
Adds an admin panel and two permissions groups for non-superusers: admin_program and income_verification_staff

- User (in `UserAdmin`) - the primary entry into the panel
    - Includes inline sections for each linked model, so all data (available to the permissions group) are accessible from this page
        - Inlines include (permissions-based) links to view identification and eligibility docs, which are pulled directly from the backend storage
        - EligibilityProgram inline includes link to `EligibilityProgramAdmin` for the user
    - Includes Django actions to mark users 'awaiting response' (a filter element for when IQ staff has reached out to the user) and 'verified' (when all documents have been reviewed and the user's income has been verified)
    - Includes custom buttons for actions that require additional data (custom buttons are initially defined in the `change_view()` function of each admin function)
        - 'Add Eligibility Program' for the user - select a new program and upload a (single) file for the user
        - 'Add IQ Program' for the user - select an IQ program that the user qualifies for and apply to it for them
- AddressRD (in `AddressAdmin`) - administration of already-submitted addresses
    - View-only page of address parts in the database
    - Editable 'City coverage' option (with proper permissions)
    - Includes Django action and custom button to re-run the GMA check
- EligibilityProgram (in `EligibilityProgramAdmin`) - eligibility program(s) for a specific user
    - Same view as the inline but extended with the ability to
        - delete eligibility programs (with permissions)
        - change the program type, e.g. from LEAP to SNAP (if the user selected the incorrect type)
- EligibilityProgramRD (in `EligibilityProgramAdmin`) - ability for admin_program staff to view/add/update eligibility programs
- IQProgramRD (in `IQProgramRDAdmin`) - ability for admin_program staff to view/add/update IQ programs
- Feedback (in `FeedbackAdmin`) - view-only page for admin_program staff to read user feedback

All updates to objects include logic for linked items (e.g. a program type change will check/update the user's `income_as_fraction_of_ami`)

This also adds a function in `tasks` to send a 'generic email', which is just a call to a SendGrid email template ID (either directly or via a var in `.env`) without parameters, with a list of recipients. The idea is to add email reminders to any staff that are added without having to make code changes.

### CODE REVIEW

**Comment by TiCampbell** [comment]
@penoptech fortunately, for all the changes, most of them are additions; there are only a few that affect the user-facing app (I think I captured all of them):

- Updated `req_` fields to `requires_` for clarity and ease of admin display (e.g. `req_is_city_covered` -> `requires_is_city_covered`)
- `backend.finalize_application()` changes
    - replaced `request` with `user` and added optional `update_user=True`
        - removes the need for a call from the user to be modified
        - the admin panel sets `update_user=False` to avoid altering the User object
    - line 1055 (`if isinstance(program, IQProgramRD) and program.enable_autoapply:`) prevents the admin panel from performing multiple applications on the same user, and I think this will also work to ensure we don't have multiple initial GTR auto-applies (that we discuss a while ago and I didn't want to put in place - I changed my mind :) )
    - added a dict of updates to the session var to the return (since `request` is no longer passed to the function)
- Centralized the dict of ordered application pages in `constants.application_pages`
- Centralized the dict of supported file extensions / content types in `constants.supported_content_types`
- Centralized the 'rent/own' and 'duration at address' form choices in `constants`
- Centralized `magic` file validation in `backend.file_validation()`
- Centralized address validation in `backend.finalize_address()`

**Comment by penoptech** [comment]
@TiCampbell, this is amazing! I was able to get into the admin panel and it is (VERY!) impressive. I found a few things listed below for your consideration. Let me know if you have any questions on them:

1. Error with `app.py` `ready` function being called during non-runserver django cli commands (A bug of my own doing. I pushed a commit to the `admin-panel-creation` branch to account for it)

2. In `ProgramChangeForm` and `EligProgramAddForm` class consider wrapping choices in `lambda` function to prevent evaluation of `EligibilityProgramRD` when the project is being setup from the ground up. This will allow you to migrate the database without an errors if you're doing the migrations for the first time

3. Running the migrations from scratch errors out in the `0020_alter_address_options_alter_addressrd_options_and_more_squashed_0030_alter_permissions_group` migration. Could use the `Permission.objects.get_or_create` to create the permissions and access the first element of the tuple so it can be used in the `permissions_list` for the respective group's permission set.

4. `backend.file_validation` there's an error calling the `read` function on the buffer. See item 6 for how to fix.

5. `application.household_members` using undefined variable `filetype`. Issue is just a bi-product of moving the file validation to the `backend.py` file. Fix might look like below in the `file_validation` function and then replace the reference to `filetype` with the `validation_message`. The problem with my suggested approach is the `validation_message` variable name. The variable name is misleading, so you might want to come up with a different approach

```python
    upper_supported_content_types = [x.upper() for x in supported_content_types.keys()]

    # Check if the filetype is in the supported_content_types
    matched_file_extension = next(
        (x for x in upper_supported_content_types if x in filetype.upper()), None
    )
    if matched_file_extension:
        return (True, matched_file_extension)
```

6. Since the `file` argument in the `file_validation` is handling two types of data (`InMemoryUploadedFile` and `bytes`) we'll need to check the data we're trying to validate

```python
    if isinstance(file, InMemoryUploadedFile):
        filetype = magic.from_buffer(file.read())
    else:
        filetype = magic.from_buffer(file)
```

7. For the user eligibility programs and IQ programs tables on the `Change user` screen, consider overriding the `has_add_permission` and returning `False`. This way the user doesn't try to add records to these tables inline, which doesn't currently work. It should be noted this does not impact the functionality of the custom buttons on the `Change user` admin page.
Screenshot 2024-04-28 at 3 56 14 PM

8. For the `Users`, `User eligibility programs`, `Feedback`, and `Addresses`, consider overriding the `has_add_permission` and returning `False`. This way the user doesn't try to add records from the side navigation or from the list views of those pages, which doesn't work. It should be noted this does not impact the functionality of the custom buttons on the `Change user` admin page.
Screenshot 2024-04-28 at 5 24 55 PM

9. Missing migration for updates to `addressrd`? It looks like it might have belong in the squashed migrations.
Screenshot 2024-04-28 at 5 26 54 PM

**Review by penoptech — CHANGES_REQUESTED** [review]
This is great! I went through the updates, did some testing and made a list of a few items to look into that are on the main thread of the PR. Check them out and let me know if you have any questions, or if any of them are off base

**Comment by TiCampbell** [comment]
@penoptech Sorry this took me so long and THANK YOU for such a detailed review! You caught some really key issues. My changes address each of your points in chronological/numerical order. The only exception is (8), where I didn't add `has_add_permission=False` to the `Addresses` page because it's a planned feature, so I left it to use an error message for the user that it's not yet available.

I also have the following additions:

- Your notes led me to realize that IQ Programs for which the user is enrolled shouldn't be able to be deleted (they must be un-enrolled first, implying communication with the program coordinator); I added an error if deletion of an already-enrolled program is attempted.
- There is a need for enrollment status to be manually updated, so I added this feature for *only superusers* (so that it can't be abused since it requires the aforementioned coordinator communication).
- Fixed bug in 'enrolled at' timezone conversion for SQLite
- Removed document viewing. I need to beef up security before this can be used
    - Malware scanning in blob storage (which is only available in Azure Commercial tenants)
    - Hosting content from a distinct domain (per https://docs.djangoproject.com/en/4.2/topics/security/#user-uploaded-content)
- Added a homegrown CSV export action, as previously discussed

Thanks!

**Review by penoptech — APPROVED** [review]

**Pull request merged**
